### ISSUE TITLE
media query match problem

### ISSUE THREAD

**Issue by vanmik** [WickyNilliams/enquire.js#34]
I build a little demo page which change background-color in dependency of media query. Here's a css:

``` css
body {
    padding:0;
    margin:0;
    background-color:yellow;
}
@media screen and (max-width: 768px) {
    body {
        background-color:green;
    }
}
@media screen and (max-width: 480px) {
    body {
        background-color:red;
    }
}
```

Now i want to match queries with enquire.js and log background-color:

``` javascript
enquire.register("screen and (max-width: 480px)", {
    match: function () {
        console.log('red')
    }
}).register("screen and (max-width: 768px)", {
    match: function () {
        console.log('green')
    },
    unmatch: function () {
        console.log('yellow')
    }
}).listen(10);
```

It works, but not in the case when you go from 'red' to 'green'. Seems like a problem with query matching.

Any suggestions?
